### ISSUE TITLE
ce account are valoarea de retras? valoarea de retras(withdraw) e un parametru la functia de withdraw

### ISSUE THREAD

**Issue by stefanbulzan** [cezarhre/curs8homework2#1]
https://github.com/cezarhre/curs8homework2/blob/6067a1afc6a23cf683be1c23471e8d7ea021e519/src/ro/fasttrackit/curs8/homework2/interfaces/BRDBank.java#L5

**Comment by cezarhre** [comment]
Am sters parametrul withdraw din state si l-am inclus in metoda
